name: Lint with Flake8

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Clear Flake8 cache
        run: rm -rf ~/.cache/flake8 || true
      - name: Lint with Flake8
        if: always()
        run: |
          flake8 $(git ls-files '*.py')
